### ISSUE TITLE
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [145, 17, 2, 16]

### ISSUE THREAD

**Issue by whiteany** [xiazhaoqiang/MULT-MicroExpressionSpot#2]
你好，我下载了[CAS(ME)^2](https://pan.baidu.com/s/1z_jB7vkoHBf5MaoQ0Ky1KQ), password:95lo，按照README配置完成后运行main.py。但是会出现报错：
Epoch 0: loss: 5.2186  cls loss: 2.5974, iou loss: 0.4818 dfl_loss: 2.8332
learning_rate: [2e-05]
Traceback (most recent call last):
  File "D:/Program Files/JetBrains/PyCharm 2023.3.2/plugins/python/helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2023.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\Administrator\Desktop\softness\final_pro\MULT-MicroExpressionSpot-main\main.py", line 100, in <module>
    main(subject, new_cfg)
  File "C:\Users\Administrator\Desktop\softness\final_pro\MULT-MicroExpressionSpot-main\main.py", line 85, in main
    out_preds = evaluation(val_loader, model, epoch, cfg)
  File "C:\Users\Administrator\Desktop\softness\final_pro\MULT-MicroExpressionSpot-main\tools\..\lib\core\function.py", line 52, in evaluation
    out_preds = model(feature)
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\softness\lib\multiprocessing\queues.py", line 241, in _feed
    send_bytes(obj)
  File "D:\ProgramData\anaconda3\envs\softness\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "D:\ProgramData\anaconda3\envs\softness\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 管道正在被关闭。
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\softness\final_pro\MULT-MicroExpressionSpot-main\tools\..\lib\models\fusemodel.py", line 637, in forward
    return self.forward_eval(x)
  File "C:\Users\Administrator\Desktop\softness\final_pro\MULT-MicroExpressionSpot-main\tools\..\lib\models\fusemodel.py", line 653, in forward_eval
    reg_dist = self.proj_conv(F.softmax(reg_dist, dim=1))
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ProgramData\anaconda3\envs\softness\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [145, 17, 2, 16]
可以麻烦您帮我看看是什么原因吗？

**Comment by whiteany** [comment]
我好像解决了，应该是我装的Pytorch版本太高了。

**Comment by xiazhaoqiang** [comment]
迟到的回复：)

> 我好像解决了，应该是我装的Pytorch版本太高了。
